### ISSUE TITLE
Replace Sami by Doctum

### ISSUE THREAD

**Issue by williamdes** [contentstack/contentstack-php#17]
Hi,
You can replace Sami by [Doctum](https://github.com/code-lts/doctum)

Ref: 65a42986f2d147788c7e5bec12c659888702b1ed

**Comment by williamdes** [comment]
cc @uttamukkoji

**Comment by uttamukkoji** [comment]
Hi @williamdes, We will check **Doctum** Doc generator. Thanks for the suggestion.

**Comment by uttamukkoji** [comment]
Hi @williamdes, 

We have updated the Doc generator from Sami to Doctum. Moving to Doctum was easy and the documentation for Doctum was helpful.

**Comment by williamdes** [comment]
> Hi @williamdes,
> 
> We have updated the Doc generator from Sami to Doctum. Moving to Doctum was easy and the documentation for Doctum was helpful.

Thank you !
By the way you can use the remote repository config to allow users browsing your docs to go to source ;)
