### ISSUE TITLE
Rename classes to uppercase.

### ISSUE THREAD

**Issue by mcarcangiu-ea** [contentstack/contentstack-php#21]
Linux environment is case sensitive and having the class contestack.php in lower case causes problems when importing the class `use Contentstack\Contentstack`.

**Comment by uttamukkoji** [comment]
Thanks @mcarcangiu-ea, for raising the issue. We’re looking into it and we’ll notify you once we incorporate the changes.

**Comment by uttamukkoji** [comment]
Closing this issue as we have updated the file name to uppercase.
