### ISSUE TITLE
 Issue with Asset class Query method

### ISSUE THREAD

**Issue by mallardduck** [contentstack/contentstack-php#4]
#### Issue description
As the title implies the current implementation of the Assets class incorrectly defines a `Query()` method which collides with the parent classes `query($_query = array())` method.

Here is the main text of the exception this throws:

> ContextErrorExceptionWarning: Declaration of Contentstack\Stack\Assets\Assets::Query() should be compatible with Contentstack\Stack\ContentType\BaseQuery\BaseQuery::query($_query = Array)

#### Steps to reproduce the issue

1.  Setup the PHP demo app - using the PR submitted there: https://github.com/contentstack/contentstack-symfony-php-blog-demo/pull/1
2. Add the current PHP SDK.
3. Insert your Stack ID and Key.
4. Run the symphony server and load the page.

#### What's the expected result?
That the library will load without exceptions.

#### What's the actual result?
The library loads with exceptions. Potentially this is specific to the version of PHP being used - it's possible that older PHP versions didn't throw and Exception here.

#### Additional details / screenshot

<img width="907" alt="console-error" src="https://user-images.githubusercontent.com/619938/46152913-06a56c00-c240-11e8-81df-fe2250f9ed5c.png">
<img width="964" alt="web-error" src="https://user-images.githubusercontent.com/619938/46152922-0a38f300-c240-11e8-86db-4d8547a0e631.png">

**Comment by ninadhatkar** [comment]
Hi @mallardduck 
Thanks for notifying this to us. We will go through this and keep posted.
